---
version: 2

jobs:
  build-publish:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "build docker image"
          command: |
            docker build -t 711fuel .
      - run:
          name: publish docker image
          environment:
            DOCKER_REPO: songgithub/7eleven-python
          command: |
            env
            docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
            docker tag 711fuel ${DOCKER_REPO}:${CIRCLE_SHA1:0:5}
            docker push ${DOCKER_REPO}:${CIRCLE_SHA1:0:5}
  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: install & execute release module
          environment:
            GH_TOKEN: ${GITHUB_TOKEN}
          command: |
            npx semantic-release

# using workflow in order to use context to inject sensitive params.
workflows:
  version: 2
  build-publish:
    jobs:
      - release:
        context: github-songgithub
      # - build-publish:
      #     # the context contains sensitive env var DOCKER_USER and DOCKER_TOKEN
      #     context: dockerhub-songgithub